# Generated by Django 3.1.2 on 2022-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_newlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlocation',
            name='base_param',
        ),
        migrations.AddField(
            model_name='newlocation',
            name='geoname_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
