# Generated by Django 3.1.2 on 2022-02-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20220215_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newlocation',
            name='geoname_id',
        ),
    ]
