# Generated by Django 3.1.2 on 2022-02-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_remove_newlocation_geoname_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoLocation',
        ),
    ]
